import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { experiment101List } from "@/data/experiment101Data";
import type { Experiment101Record } from "@/hooks/useExperiment101Progress";

export interface ReportRow {
  title: string;
  status: "Completed" | "Not started";
  score: number;
  total: number;
  percentage: number;
  outcome: "Passed" | "Not passed" | "—";
}

export interface ReportMeta {
  learnerName: string;
  passingScore?: number;
}

export function buildReportRows(records: Record<string, Experiment101Record>): ReportRow[] {
  return experiment101List.map((exp) => {
    const record = records[exp.id];
    const score = record?.quizScore ?? 0;
    const total = record?.quizTotal ?? 0;
    const percentage = total > 0 ? Math.round((score / total) * 100) : 0;
    return {
      title: exp.title,
      status: record?.completed ? "Completed" : "Not started",
      score,
      total,
      percentage,
      outcome: total === 0 ? "—" : percentage >= 70 ? "Passed" : "Not passed",
    };
  });
}

function summary(rows: ReportRow[]) {
  const completed = rows.filter((r) => r.status === "Completed").length;
  const attempted = rows.filter((r) => r.total > 0);
  const average = attempted.length
    ? Math.round(attempted.reduce((sum, r) => sum + r.percentage, 0) / attempted.length)
    : 0;
  return { completed, total: rows.length, average };
}

export function exportReportCSV(rows: ReportRow[], meta: ReportMeta): void {
  const stats = summary(rows);
  const lines = [
    ["VirtuLab — Experiment 101 progress report"],
    ["Learner", meta.learnerName],
    ["Generated", new Date().toISOString()],
    ["Experiments completed", `${stats.completed} of ${stats.total}`],
    ["Average quiz score", `${stats.average}%`],
    [],
    ["Experiment", "Status", "Score", "Out of", "Percentage", "Outcome"],
    ...rows.map((r) => [r.title, r.status, String(r.score), String(r.total), `${r.percentage}%`, r.outcome]),
  ];

  const csv = lines
    .map((cells) => cells.map((cell) => `"${String(cell ?? "").replace(/"/g, '""')}"`).join(","))
    .join("\n");

  const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `experiment-101-progress-${new Date().toISOString().slice(0, 10)}.csv`;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

export function exportReportPDF(rows: ReportRow[], meta: ReportMeta): void {
  const stats = summary(rows);
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header band
  doc.setFillColor(22, 32, 56);
  doc.rect(0, 0, pageWidth, 96, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("VirtuLab", 40, 44);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.text("Experiment 101 — Learner progress report", 40, 68);

  doc.setTextColor(30, 30, 30);
  doc.setFontSize(11);
  doc.text(`Learner: ${meta.learnerName}`, 40, 132);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 40, 150);
  doc.text(`Experiments completed: ${stats.completed} of ${stats.total}`, 40, 168);
  doc.text(`Average quiz score: ${stats.average}%`, 40, 186);

  autoTable(doc, {
    startY: 210,
    head: [["Experiment", "Status", "Score", "Percentage", "Outcome"]],
    body: rows.map((r) => [
      r.title,
      r.status,
      r.total ? `${r.score} / ${r.total}` : "—",
      r.total ? `${r.percentage}%` : "—",
      r.outcome,
    ]),
    styles: { fontSize: 10, cellPadding: 6 },
    headStyles: { fillColor: [22, 199, 154], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    margin: { left: 40, right: 40 },
  });

  const endY = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? 300;
  doc.setFontSize(9);
  doc.setTextColor(110, 110, 110);
  doc.text(
    "Generated by VirtuLab — a free, ad-free virtual science laboratory. Pass mark 70%.",
    40,
    Math.min(endY + 30, doc.internal.pageSize.getHeight() - 40),
  );

  doc.save(`experiment-101-progress-${new Date().toISOString().slice(0, 10)}.pdf`);
}
